Feature/train 266
r-barlow/train-react-insight pull request #4
Opened 2023-05-08 09:20 UTC by r-barlow

2023-05-11 07:41 UTC, colsen-neslo requested changes

2023-05-11 07:41 UTC, colsen-neslo commented on src/container/Login.container.jsx
> +        }
I am not sure if you have looked at any training material with regards to the redux-saga pattern? So we like to follow this pattern whereby we get our containers to dispatch actions that sagas will watch for. The saga will then perform http requests with axios and then we use redux state management to help manage application state.

Please read up on some of that and you can come back and modify the current implementation to use the redux-saga pattern in a separate task.

2023-05-11 07:41 UTC, colsen-neslo commented on src/container/Login.container.jsx
> +    }, []);
So another way to further improve this is if you have a form state object that holds the username and password values as fields, you can then create a single on change function that can consume the field name and the value and you can perform a single on change like something below, where the `newState` value represents something like `{ username: 'exampleusername' }` 
```suggestion
    const onChange = (newState) => {
        setForm({ ...form, ...newState });
    };
```

2023-05-11 07:41 UTC, colsen-neslo commented on src/container/Login.container.jsx
> +        <>
You can remove the react fragment if you are only returning a single element.

2023-05-11 07:41 UTC, colsen-neslo commented on src/page/Login.jsx
> +            <div className="login__card">
The card can be defined as an article element.
```suggestion
            <article className="login__card">
```

2023-05-11 07:41 UTC, colsen-neslo commented on src/page/Login.jsx
> +        <div className="login__card__frame">
You can make this a section.
```suggestion
        <section className="login__card__frame">
```

2023-05-11 07:41 UTC, colsen-neslo commented on src/page/Login.jsx
> +        <div className="login__background"></div>
You can self close an empty tag.
```suggestion
        <div className="login__background" />
```

2023-05-11 07:41 UTC, colsen-neslo commented on src/stylesheet/00_settings/_dimen.scss
> +$login: (
What is the purpose of this file? Does it just define dimension variables for certain components?
If so why not just define them in the component stylesheets as these should never be accessed out the scope of the login component?

2023-05-11 07:41 UTC, colsen-neslo commented on src/tool/auth.util.jsx
> +}
As mentioned earlier, once you implement redux-saga patterns this http call will be replaced by the saga that contains the axios http call to the API.

2023-05-11 09:13 UTC, colsen-neslo requested changes

2023-05-11 09:13 UTC, colsen-neslo commented on src/component/form/input.scss
> +$dimen: (
Is this necessary, can you not define it inline below where required?

2023-05-11 09:13 UTC, colsen-neslo commented on src/component/ui/tooltip.scss
> +$dimen: (
Same as above?

2023-05-11 09:13 UTC, colsen-neslo commented on src/page/Login.jsx
> +                <div className="login__card__body">
Is this div necessary? I think we can remove this if there's no specific reason to have it.

2023-05-11 09:13 UTC, colsen-neslo commented on src/page/login.scss
> +$dimen: (
Same question as previous styles?

2023-05-11 09:47 UTC, colsen-neslo approved these changes

2023-05-12 08:56 UTC, JOlsen-Neslo requested changes

2023-05-12 08:56 UTC, JOlsen-Neslo commented on src/component/form/Input.js
> +    }
We tend to refrain from following this sort of pattern, namely `Indirection`, as this doesn't make it clear what the flow of the markup is going to follow. Creating functions that render JSX generally means we should rather be creating a private component to render this markup

2023-05-12 08:56 UTC, JOlsen-Neslo commented on src/component/form/Input.js
> +            <div className="form__input-error__image__frame">
If you are following the BEM structure for your styling, this breaks those rules. It should always be `block__element--modifer`

What this looks like is `block_element_element_element`

2023-05-12 08:56 UTC, JOlsen-Neslo commented on src/component/form/Input.js
> +                <img className="form__input-error__image" src="/images/error.svg" alt="input error"/>
Rather import your SVG as a component

`import { ReactComponent as ErrorIcon } from '../images/error.svg';`

You can then render it like this:

`<ErrorIcon />`

2023-05-12 14:43 UTC, JOlsen-Neslo requested changes

2023-05-12 14:43 UTC, JOlsen-Neslo commented on src/component/form/Input.jsx
> +};
When there is no JavaScript in the component, no need for curly braces

```suggestion
const Input = ({type, placeholder, hasError, onChange}) => 
     <div className="form__input__group">
          <input type={type}
                 className={`form__control${hasError ? " form__input__error" : ""}`}
                 placeholder={placeholder}
                 aria-label={placeholder}
                 onChange={e => {
                     onChange(e.target.value);
                 }}/>
          {hasError ? <InputRequired/> : null}
      </div>
);
```

2023-05-12 14:43 UTC, JOlsen-Neslo commented on src/component/form/InputRequired.jsx
> +const InputRequired = () => {
Same comment here

2023-05-16 08:20 UTC, JOlsen-Neslo requested changes

2023-05-16 08:20 UTC, JOlsen-Neslo commented on src/component/form/InputRequired.jsx
> +        <ErrorIcon className="form__input__error__image" alt="input error"/>
These classes both don't follow the BEM structure

2023-05-16 08:20 UTC, JOlsen-Neslo commented on src/page/Login.jsx
> +        <section className="login__card__frame">
a few classes in this file also don't follow BEM

2023-05-17 12:44 UTC, JOlsen-Neslo approved these changes

2023-05-17 12:44 UTC, merged