TRAIN-270: Add base app navigation.
r-barlow/train-react-insight pull request #9
Opened 2023-05-25 11:55 UTC by r-barlow

2023-05-25 12:01 UTC, colsen-neslo commented on src/page/AppLayout.js
> +    let nav = NAVIGATION_ITEMS.find(item => `/${item.tag}` === window.location.pathname);
You should be able to leverage the react-router to check the current path. I am just not certain of the exact syntax but I think they have a hook to leverage from.

2023-05-25 12:06 UTC, colsen-neslo approved these changes

2023-05-25 12:45 UTC, JOlsen-Neslo requested changes
Nice job implementing the context API 👏

2023-05-25 12:45 UTC, JOlsen-Neslo commented on src/page/AppLayout.js
> +    }
Since this is navigation specific logic, the ideal pattern would be to create a `NavigationProvider` to contain this. The AppLayout shouldn't care about it, only render it.

2023-05-25 12:45 UTC, JOlsen-Neslo commented on src/component/navigation/Navigation.jsx
> +    const {nav} = useContext(NavigationContext);
Rather define a new hook for this, so you can also check if the context is not defined and then throw an error. Just a good pattern follow for defensive coding using the context pattern

2023-05-26 12:42 UTC, JOlsen-Neslo approved these changes

2023-05-26 12:42 UTC, merged